### ISSUE TITLE
Pinger-Expansion issues. Placeholder isonline/online always shows offline for my server.

### ISSUE THREAD

**Issue by mrFavoslav** [HappyAreaBean/ServerPinger-PAPI-Expansion#2]
# Pinger/ServerPinger placeholder is broken. 

## Proxy 
> Waterfall build number 475
> log - https://paste.helpch.at/dupidilesa.md

## Server
> paper-spigot 1.16.5 latest
> log - https://paste.helpch.at/unehiteget.md

## Additional Info
> Whole server runs on Pterodactyl Panel
> Operating System is Ubuntu Server 20.04.4
> DNS is through CloudFlare
> Domain Name is from Freenom

## /papi dump
> https://paste.helpch.at/uhinerisig (without serverpinger)
> https://paste.helpch.at/acakujaxom

## Placeholder
> %serverpinger_isonline_large-lands.tk:60002% / %serverpinger_online_large-lands.tk:60002% also tried %pinger_isonline_large-lands.tk:60002% / %pinger_online_large-lands.tk:60002%

## Issue = placeholder always says my server is offline

when i try to ping my server (bungee, authme, lobby) it is always Offline. When i tried to ping.. for example mc.qplay.cz it is Online but when i try large-lands.tk:60002 (which is my server lobby-2) it is Offline. 

What should i do?

**Comment by HappyAreaBean** [comment]
If your DNS is through Cloudflare, you should use a numeric IP instead of a domain name.
Also, if you are using your public IP address as an address, you should make sure that address is publicly accessible, e.g. `1.2.3.4:60002`. 

However, for security reasons, I do not recommend opening all servers from the outside world while running BungeeCord.
https://pterodactyl.io/community/games/minecraft.html#configuring-a-server-network-bungeecord-waterfall-hexacord-etc

**Comment by HappyAreaBean** [comment]
In my case, I still find this problem when I follow the settings and use a specific IP. But since I have multiple nodes and my bungeecord is hosted externally, my server needs to allow external connections in order for bungeecord to connect to my server. So, I changed wings network mode to host mode. I have been using private IPs to show online status between each server and it works well.

**Comment by mrFavoslav** [comment]
Private IP.. i'm just an idiot.. why i didn't try Private IP? now it works fine https://ctrlv.cz/2A1D

Thank you.. xd
